/* generated configuration header file - do not edit */
#ifndef BSP_MCU_CPU_MEMORY_CFG_H_
#define BSP_MCU_CPU_MEMORY_CFG_H_
#define BSP_CFG_CPU_MPU_ATTR0_TYPE            (BSP_TYPE_NORMAL_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR0_INNER           (BSP_WRITE_BACK_NON_TRANSIENT)
      #define BSP_CFG_CPU_MPU_ATTR0_INNER_READ      (BSP_READ_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR0_INNER_WRITE     (BSP_WRITE_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR0_OUTER           (BSP_WRITE_BACK_NON_TRANSIENT)
      #define BSP_CFG_CPU_MPU_ATTR0_OUTER_READ      (BSP_READ_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR0_OUTER_WRITE     (BSP_WRITE_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR0_DEVICE_TYPE     (BSP_DEVICE_NGNRNE)

      #define BSP_CFG_CPU_MPU_ATTR1_TYPE            (BSP_TYPE_NORMAL_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR1_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR1_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR1_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR1_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR1_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR1_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR1_DEVICE_TYPE     (BSP_DEVICE_NGNRNE)

      #define BSP_CFG_CPU_MPU_ATTR2_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR2_INNER           (BSP_WRITE_BACK_NON_TRANSIENT)
      #define BSP_CFG_CPU_MPU_ATTR2_INNER_READ      (BSP_READ_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR2_INNER_WRITE     (BSP_WRITE_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR2_OUTER           (BSP_WRITE_BACK_NON_TRANSIENT)
      #define BSP_CFG_CPU_MPU_ATTR2_OUTER_READ      (BSP_READ_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR2_OUTER_WRITE     (BSP_WRITE_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR2_DEVICE_TYPE     (BSP_DEVICE_NGNRNE)

      #define BSP_CFG_CPU_MPU_ATTR3_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR3_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR3_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR3_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR3_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR3_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR3_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR3_DEVICE_TYPE     (BSP_DEVICE_NGNRE)

      #define BSP_CFG_CPU_MPU_ATTR4_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR4_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR4_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR4_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR4_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR4_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR4_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR4_DEVICE_TYPE     (BSP_DEVICE_NGRE)

      #define BSP_CFG_CPU_MPU_ATTR5_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR5_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR5_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR5_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR5_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR5_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR5_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR5_DEVICE_TYPE     (BSP_DEVICE_GRE)

      #define BSP_CFG_CPU_MPU_ATTR6_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR6_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR6_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR6_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR6_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR6_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR6_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR6_DEVICE_TYPE     (BSP_DEVICE_NGNRNE)

      #define BSP_CFG_CPU_MPU_ATTR7_TYPE            (BSP_TYPE_DEVICE_MEMORY)
      #define BSP_CFG_CPU_MPU_ATTR7_INNER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR7_INNER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR7_INNER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR7_OUTER           (BSP_NON_CACHEABLE)
      #define BSP_CFG_CPU_MPU_ATTR7_OUTER_READ      (BSP_READ_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR7_OUTER_WRITE     (BSP_WRITE_NOT_ALLOCATE)
      #define BSP_CFG_CPU_MPU_ATTR7_DEVICE_TYPE     (BSP_DEVICE_NGNRNE)

      /* Region00: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION00_VADDR            (0x00000000)
      #define BSP_CFG_EL3_MMU_REGION00_PADDR            (0x00000000)
      #define BSP_CFG_EL3_MMU_REGION00_SIZE             (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION00_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION00_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION00_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION00_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION00_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION00_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION00_ENABLE           (BSP_REGION_DISABLE)

      /* Region01: System SRAM */
      #define BSP_CFG_EL3_MMU_REGION01_VADDR            (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION01_PADDR            (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION01_SIZE             (0x00200000)
      #define BSP_CFG_EL3_MMU_REGION01_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION01_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION01_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION01_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION01_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION01_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION01_ENABLE           (BSP_REGION_ENABLE)

      /* Region02: System SRAM mirror */
      #define BSP_CFG_EL3_MMU_REGION02_VADDR            (0x10200000)
      #define BSP_CFG_EL3_MMU_REGION02_PADDR            (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION02_SIZE             (0x00200000)
      #define BSP_CFG_EL3_MMU_REGION02_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION02_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION02_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION02_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION02_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION02_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION02_ENABLE           (BSP_REGION_ENABLE)

      /* Region03: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION03_VADDR            (0x10400000)
      #define BSP_CFG_EL3_MMU_REGION03_PADDR            (0x10400000)
      #define BSP_CFG_EL3_MMU_REGION03_SIZE             (0x0FC00000)
      #define BSP_CFG_EL3_MMU_REGION03_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION03_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION03_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION03_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION03_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION03_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION03_ENABLE           (BSP_REGION_DISABLE)

      /* Region04: Cortex-R52 CPU TCM via AXIS */
      #define BSP_CFG_EL3_MMU_REGION04_VADDR            (0x20000000)
      #define BSP_CFG_EL3_MMU_REGION04_PADDR            (0x20000000)
      #define BSP_CFG_EL3_MMU_REGION04_SIZE             (0x01200000)
      #define BSP_CFG_EL3_MMU_REGION04_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION04_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION04_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION04_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION04_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION04_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION04_ENABLE           (BSP_REGION_ENABLE)

      /* Region05: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION05_VADDR            (0x21200000)
      #define BSP_CFG_EL3_MMU_REGION05_PADDR            (0x21200000)
      #define BSP_CFG_EL3_MMU_REGION05_SIZE             (0x0EE00000)
      #define BSP_CFG_EL3_MMU_REGION05_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION05_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION05_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION05_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION05_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION05_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION05_ENABLE           (BSP_REGION_DISABLE)

      /* Region06: External address space xSPI0 CS0 mirror */
      #define BSP_CFG_EL3_MMU_REGION06_VADDR            (0x30000000)
      #define BSP_CFG_EL3_MMU_REGION06_PADDR            (0x40000000)
      #define BSP_CFG_EL3_MMU_REGION06_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION06_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION06_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION06_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION06_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION06_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION06_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION06_ENABLE           (BSP_REGION_ENABLE)

      /* Region07: External address space xSPI0 CS1 mirror */
      #define BSP_CFG_EL3_MMU_REGION07_VADDR            (0x38000000)
      #define BSP_CFG_EL3_MMU_REGION07_PADDR            (0x48000000)
      #define BSP_CFG_EL3_MMU_REGION07_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION07_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION07_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION07_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION07_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION07_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION07_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION07_ENABLE           (BSP_REGION_ENABLE)

      /* Region08: External address space xSPI0 CS0 */
      #define BSP_CFG_EL3_MMU_REGION08_VADDR            (0x40000000)
      #define BSP_CFG_EL3_MMU_REGION08_PADDR            (0x40000000)
      #define BSP_CFG_EL3_MMU_REGION08_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION08_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION08_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION08_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION08_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION08_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION08_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION08_ENABLE           (BSP_REGION_ENABLE)

      /* Region09: External address space xSPI0 CS1 */
      #define BSP_CFG_EL3_MMU_REGION09_VADDR            (0x48000000)
      #define BSP_CFG_EL3_MMU_REGION09_PADDR            (0x48000000)
      #define BSP_CFG_EL3_MMU_REGION09_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION09_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION09_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION09_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION09_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION09_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION09_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION09_ENABLE           (BSP_REGION_ENABLE)

      /* Region10: External address space xSPI1 CS0 */
      #define BSP_CFG_EL3_MMU_REGION10_VADDR            (0x50000000)
      #define BSP_CFG_EL3_MMU_REGION10_PADDR            (0x50000000)
      #define BSP_CFG_EL3_MMU_REGION10_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION10_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION10_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION10_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION10_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION10_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION10_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION10_ENABLE           (BSP_REGION_ENABLE)

      /* Region11: External address space xSPI1 CS1 */
      #define BSP_CFG_EL3_MMU_REGION11_VADDR            (0x58000000)
      #define BSP_CFG_EL3_MMU_REGION11_PADDR            (0x58000000)
      #define BSP_CFG_EL3_MMU_REGION11_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION11_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION11_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION11_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION11_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION11_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION11_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION11_ENABLE           (BSP_REGION_ENABLE)

      /* Region12: External address space xSPI1 CS0 mirror */
      #define BSP_CFG_EL3_MMU_REGION12_VADDR            (0x60000000)
      #define BSP_CFG_EL3_MMU_REGION12_PADDR            (0x50000000)
      #define BSP_CFG_EL3_MMU_REGION12_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION12_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION12_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION12_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION12_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION12_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION12_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION12_ENABLE           (BSP_REGION_ENABLE)

      /* Region13: External address space xSPI1 CS1 mirror */
      #define BSP_CFG_EL3_MMU_REGION13_VADDR            (0x68000000)
      #define BSP_CFG_EL3_MMU_REGION13_PADDR            (0x58000000)
      #define BSP_CFG_EL3_MMU_REGION13_SIZE             (0x08000000)
      #define BSP_CFG_EL3_MMU_REGION13_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION13_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION13_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION13_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION13_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION13_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION13_ENABLE           (BSP_REGION_ENABLE)

      /* Region14: External address space CS0 */
      #define BSP_CFG_EL3_MMU_REGION14_VADDR            (0x70000000)
      #define BSP_CFG_EL3_MMU_REGION14_PADDR            (0x70000000)
      #define BSP_CFG_EL3_MMU_REGION14_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION14_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION14_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION14_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION14_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION14_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION14_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION14_ENABLE           (BSP_REGION_ENABLE)

      /* Region15: External address space CS2 */
      #define BSP_CFG_EL3_MMU_REGION15_VADDR            (0x74000000)
      #define BSP_CFG_EL3_MMU_REGION15_PADDR            (0x74000000)
      #define BSP_CFG_EL3_MMU_REGION15_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION15_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION15_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION15_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION15_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION15_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION15_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION15_ENABLE           (BSP_REGION_ENABLE)

      /* Region16: External address space CS3 */
      #define BSP_CFG_EL3_MMU_REGION16_VADDR            (0x78000000)
      #define BSP_CFG_EL3_MMU_REGION16_PADDR            (0x78000000)
      #define BSP_CFG_EL3_MMU_REGION16_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION16_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION16_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION16_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION16_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION16_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION16_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION16_ENABLE           (BSP_REGION_ENABLE)

      /* Region17: External address space CS5 */
      #define BSP_CFG_EL3_MMU_REGION17_VADDR            (0x7C000000)
      #define BSP_CFG_EL3_MMU_REGION17_PADDR            (0x7C000000)
      #define BSP_CFG_EL3_MMU_REGION17_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION17_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION17_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION17_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION17_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION17_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION17_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION17_ENABLE           (BSP_REGION_ENABLE)

      /* Region18: Non-Safety Peripheral 0 */
      #define BSP_CFG_EL3_MMU_REGION18_VADDR            (0x80000000)
      #define BSP_CFG_EL3_MMU_REGION18_PADDR            (0x80000000)
      #define BSP_CFG_EL3_MMU_REGION18_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION18_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION18_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION18_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION18_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION18_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION18_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION18_ENABLE           (BSP_REGION_ENABLE)

      /* Region19: R-Bus Safety Peripheral */
      #define BSP_CFG_EL3_MMU_REGION19_VADDR            (0x81000000)
      #define BSP_CFG_EL3_MMU_REGION19_PADDR            (0x81000000)
      #define BSP_CFG_EL3_MMU_REGION19_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION19_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION19_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION19_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION19_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION19_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION19_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION19_ENABLE           (BSP_REGION_ENABLE)

      /* Region20: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION20_VADDR            (0x82000000)
      #define BSP_CFG_EL3_MMU_REGION20_PADDR            (0x82000000)
      #define BSP_CFG_EL3_MMU_REGION20_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION20_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION20_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION20_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION20_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION20_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION20_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION20_ENABLE           (BSP_REGION_DISABLE)

      /* Region21: GIC600 */
      #define BSP_CFG_EL3_MMU_REGION21_VADDR            (0x83000000)
      #define BSP_CFG_EL3_MMU_REGION21_PADDR            (0x83000000)
      #define BSP_CFG_EL3_MMU_REGION21_SIZE             (0x00200000)
      #define BSP_CFG_EL3_MMU_REGION21_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION21_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION21_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION21_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION21_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION21_ATTRINDEX        (BSP_ATTRINDEX2)
      #define BSP_CFG_EL3_MMU_REGION21_ENABLE           (BSP_REGION_ENABLE)

      /* Region22: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION22_VADDR            (0x83200000)
      #define BSP_CFG_EL3_MMU_REGION22_PADDR            (0x83200000)
      #define BSP_CFG_EL3_MMU_REGION22_SIZE             (0x00E00000)
      #define BSP_CFG_EL3_MMU_REGION22_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION22_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION22_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION22_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION22_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION22_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION22_ENABLE           (BSP_REGION_DISABLE)

      /* Region23: External address space CS0 mirror */
      #define BSP_CFG_EL3_MMU_REGION23_VADDR            (0x84000000)
      #define BSP_CFG_EL3_MMU_REGION23_PADDR            (0x70000000)
      #define BSP_CFG_EL3_MMU_REGION23_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION23_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION23_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION23_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION23_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION23_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION23_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION23_ENABLE           (BSP_REGION_ENABLE)

      /* Region24: R-Bus Non-Safety Peripheral 1 */
      #define BSP_CFG_EL3_MMU_REGION24_VADDR            (0x88000000)
      #define BSP_CFG_EL3_MMU_REGION24_PADDR            (0x88000000)
      #define BSP_CFG_EL3_MMU_REGION24_SIZE             (0x02000000)
      #define BSP_CFG_EL3_MMU_REGION24_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION24_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION24_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION24_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION24_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION24_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION24_ENABLE           (BSP_REGION_ENABLE)

      /* Region25: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION25_VADDR            (0x8A000000)
      #define BSP_CFG_EL3_MMU_REGION25_PADDR            (0x8A000000)
      #define BSP_CFG_EL3_MMU_REGION25_SIZE             (0x02000000)
      #define BSP_CFG_EL3_MMU_REGION25_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION25_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION25_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION25_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION25_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION25_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION25_ENABLE           (BSP_REGION_DISABLE)

      /* Region26: Debug Private */
      #define BSP_CFG_EL3_MMU_REGION26_VADDR            (0x8C000000)
      #define BSP_CFG_EL3_MMU_REGION26_PADDR            (0x8C000000)
      #define BSP_CFG_EL3_MMU_REGION26_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION26_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION26_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION26_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION26_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION26_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION26_ATTRINDEX        (BSP_ATTRINDEX2)
      #define BSP_CFG_EL3_MMU_REGION26_ENABLE           (BSP_REGION_ENABLE)

      /* Region27: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION27_VADDR            (0x8D000000)
      #define BSP_CFG_EL3_MMU_REGION27_PADDR            (0x8D000000)
      #define BSP_CFG_EL3_MMU_REGION27_SIZE             (0x03000000)
      #define BSP_CFG_EL3_MMU_REGION27_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION27_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION27_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION27_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION27_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION27_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION27_ENABLE           (BSP_REGION_DISABLE)

      /* Region28: LLPP Peripheral */
      #define BSP_CFG_EL3_MMU_REGION28_VADDR            (0x90000000)
      #define BSP_CFG_EL3_MMU_REGION28_PADDR            (0x90000000)
      #define BSP_CFG_EL3_MMU_REGION28_SIZE             (0x00400000)
      #define BSP_CFG_EL3_MMU_REGION28_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION28_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION28_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION28_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION28_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION28_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION28_ENABLE           (BSP_REGION_ENABLE)

      /* Region29: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION29_VADDR            (0x90400000)
      #define BSP_CFG_EL3_MMU_REGION29_PADDR            (0x90400000)
      #define BSP_CFG_EL3_MMU_REGION29_SIZE             (0x01C00000)
      #define BSP_CFG_EL3_MMU_REGION29_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION29_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION29_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION29_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION29_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION29_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION29_ENABLE           (BSP_REGION_DISABLE)

      /* Region30: A-Bus Peripheral */
      #define BSP_CFG_EL3_MMU_REGION30_VADDR            (0x92000000)
      #define BSP_CFG_EL3_MMU_REGION30_PADDR            (0x92000000)
      #define BSP_CFG_EL3_MMU_REGION30_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION30_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION30_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION30_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION30_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION30_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION30_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION30_ENABLE           (BSP_REGION_ENABLE)

      /* Region31: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION31_VADDR            (0x93000000)
      #define BSP_CFG_EL3_MMU_REGION31_PADDR            (0x93000000)
      #define BSP_CFG_EL3_MMU_REGION31_SIZE             (0x01000000)
      #define BSP_CFG_EL3_MMU_REGION31_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION31_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION31_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION31_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION31_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION31_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION31_ENABLE           (BSP_REGION_DISABLE)

      /* Region32: External address space CS2 mirror */
      #define BSP_CFG_EL3_MMU_REGION32_VADDR            (0x94000000)
      #define BSP_CFG_EL3_MMU_REGION32_PADDR            (0x74000000)
      #define BSP_CFG_EL3_MMU_REGION32_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION32_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION32_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION32_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION32_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION32_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION32_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION32_ENABLE           (BSP_REGION_ENABLE)

      /* Region33: External address space CS3 mirror */
      #define BSP_CFG_EL3_MMU_REGION33_VADDR            (0x98000000)
      #define BSP_CFG_EL3_MMU_REGION33_PADDR            (0x78000000)
      #define BSP_CFG_EL3_MMU_REGION33_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION33_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION33_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION33_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION33_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION33_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION33_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION33_ENABLE           (BSP_REGION_ENABLE)

      /* Region34: External address space CS5 mirror */
      #define BSP_CFG_EL3_MMU_REGION34_VADDR            (0x9C000000)
      #define BSP_CFG_EL3_MMU_REGION34_PADDR            (0x7C000000)
      #define BSP_CFG_EL3_MMU_REGION34_SIZE             (0x04000000)
      #define BSP_CFG_EL3_MMU_REGION34_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION34_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION34_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION34_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION34_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION34_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION34_ENABLE           (BSP_REGION_ENABLE)

      /* Region35: PCIE0 mirror */
      #define BSP_CFG_EL3_MMU_REGION35_VADDR            (0xA0000000)
      #define BSP_CFG_EL3_MMU_REGION35_PADDR            (0xA0000000)
      #define BSP_CFG_EL3_MMU_REGION35_SIZE             (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION35_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION35_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION35_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION35_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION35_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION35_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION35_ENABLE           (BSP_REGION_ENABLE)

      /* Region36: PCIE1 mirror */
      #define BSP_CFG_EL3_MMU_REGION36_VADDR            (0xB0000000)
      #define BSP_CFG_EL3_MMU_REGION36_PADDR            (0xB0000000)
      #define BSP_CFG_EL3_MMU_REGION36_SIZE             (0x10000000)
      #define BSP_CFG_EL3_MMU_REGION36_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION36_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION36_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION36_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION36_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION36_ATTRINDEX        (BSP_ATTRINDEX1)
      #define BSP_CFG_EL3_MMU_REGION36_ENABLE           (BSP_REGION_ENABLE)

      /* Region37: DDR mirror */
      #define BSP_CFG_EL3_MMU_REGION37_VADDR            (0xC0000000)
      #define BSP_CFG_EL3_MMU_REGION37_PADDR            (0xC0000000)
      #define BSP_CFG_EL3_MMU_REGION37_SIZE             (0x40000000)
      #define BSP_CFG_EL3_MMU_REGION37_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION37_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION37_SH               (BSP_OUTER_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION37_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION37_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION37_ATTRINDEX        (BSP_ATTRINDEX3)
      #define BSP_CFG_EL3_MMU_REGION37_ENABLE           (BSP_REGION_ENABLE)

      /* Region38: Reserved Area */
      #define BSP_CFG_EL3_MMU_REGION38_VADDR            (0x100000000)
      #define BSP_CFG_EL3_MMU_REGION38_PADDR            (0x100000000)
      #define BSP_CFG_EL3_MMU_REGION38_SIZE             (0x100000000)
      #define BSP_CFG_EL3_MMU_REGION38_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION38_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION38_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION38_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION38_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION38_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION38_ENABLE           (BSP_REGION_DISABLE)

      /* Region39: DDR */
      #define BSP_CFG_EL3_MMU_REGION39_VADDR            (0x200000000)
      #define BSP_CFG_EL3_MMU_REGION39_PADDR            (0x200000000)
      #define BSP_CFG_EL3_MMU_REGION39_SIZE             (0x200000000)
      #define BSP_CFG_EL3_MMU_REGION39_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION39_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION39_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION39_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION39_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION39_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION39_ENABLE           (BSP_REGION_ENABLE)

      /* Region40: PCIE0 */
      #define BSP_CFG_EL3_MMU_REGION40_VADDR            (0x400000000)
      #define BSP_CFG_EL3_MMU_REGION40_PADDR            (0x400000000)
      #define BSP_CFG_EL3_MMU_REGION40_SIZE             (0x200000000)
      #define BSP_CFG_EL3_MMU_REGION40_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION40_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION40_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION40_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION40_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION40_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION40_ENABLE           (BSP_REGION_ENABLE)

      /* Region41: PCIE1 */
      #define BSP_CFG_EL3_MMU_REGION41_VADDR            (0x600000000)
      #define BSP_CFG_EL3_MMU_REGION41_PADDR            (0x600000000)
      #define BSP_CFG_EL3_MMU_REGION41_SIZE             (0x200000000)
      #define BSP_CFG_EL3_MMU_REGION41_UXN              (BSP_UXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION41_PXN              (BSP_PXN_EXECUTE_ENABLE)
      #define BSP_CFG_EL3_MMU_REGION41_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION41_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION41_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION41_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION41_ENABLE           (BSP_REGION_ENABLE)

      /* Region42: Not Use */
      #define BSP_CFG_EL3_MMU_REGION42_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION42_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION42_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION42_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION42_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION42_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION42_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION42_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION42_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION42_ENABLE           (BSP_REGION_DISABLE)

      /* Region43: Not Use */
      #define BSP_CFG_EL3_MMU_REGION43_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION43_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION43_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION43_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION43_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION43_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION43_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION43_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION43_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION43_ENABLE           (BSP_REGION_DISABLE)

      /* Region44: Not Use */
      #define BSP_CFG_EL3_MMU_REGION44_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION44_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION44_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION44_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION44_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION44_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION44_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION44_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION44_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION44_ENABLE           (BSP_REGION_DISABLE)

      /* Region45: Not Use */
      #define BSP_CFG_EL3_MMU_REGION45_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION45_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION45_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION45_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION45_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION45_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION45_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION45_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION45_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION45_ENABLE           (BSP_REGION_DISABLE)

      /* Region46: Not Use */
      #define BSP_CFG_EL3_MMU_REGION46_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION46_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION46_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION46_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION46_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION46_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION46_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION46_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION46_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION46_ENABLE           (BSP_REGION_DISABLE)

      /* Region47: Not Use */
      #define BSP_CFG_EL3_MMU_REGION47_VADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION47_PADDR            (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION47_SIZE             (0x000000000)
      #define BSP_CFG_EL3_MMU_REGION47_UXN              (BSP_UXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION47_PXN              (BSP_PXN_EXECUTE_DISABLE)
      #define BSP_CFG_EL3_MMU_REGION47_SH               (BSP_NON_SHAREABLE)
      #define BSP_CFG_EL3_MMU_REGION47_AP               (BSP_EL321RW_EL0RW)
      #define BSP_CFG_EL3_MMU_REGION47_NS               (BSP_NS_SECURE)
      #define BSP_CFG_EL3_MMU_REGION47_ATTRINDEX        (BSP_ATTRINDEX0)
      #define BSP_CFG_EL3_MMU_REGION47_ENABLE           (BSP_REGION_DISABLE)
#endif /* BSP_MCU_CPU_MEMORY_CFG_H_ */
